#!/bin/bash
# Case to update different stuff quickly
function upd {
    function guiki { echo "Actualizando güiki" && git -C ~/guiki pull }
    function dots { echo "Actualizando dots" && git -C ~/dots pull }
    function sistema { echo "Actualizando sistema" && yay }
    function vim { echo "Actualizando plugins de vim" && echo "no funciona aún" }
    echo "¿Qué actualizamos?
    s) Sistema
    v) Plugins de Vim
    r) Repositorios de git
       g) guiki
       d) dots
    A) Todo lo anterior
    n) nada"
    read opt 
    case $opt in
        s)
	    sistema
	    ;;
        v)
	    vim
	    ;;
	g)
	    guiki
	    ;;
	d)
	    dots
	    ;;
	r)
	    guiki
	    dots
	    ;;
	[Aa])
	    sistema
	    vim
	    guiki
	    dots
	    ;;
	n)
	    echo "Ok" 
	    ;;
	*)
	    echo "Mira a ver en que la has liado"
	    ;;
    esac
}
