schemes:
  gruvoxdark: &gruvboxdark
  # Colors (Gruvbox dark)
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'
     
      # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
     
      # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  gruvboxlight: &gruvboxlight
  # Default colors
    primary:
      # hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'
    
    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
    
    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

  konsolegreenblack: &kgreenblack
  # Default colors
    primary:
      # hard contrast: background
      background: '#000000'
      # soft contrast: background
      foreground: '#18f018'
    cursor:
      cursor:  '#18f018'
    # Normal colors
    normal:
      black:   '#000000'
      red:     '#b21818'
      green:   '#18b218'
      yellow:  '#b26818'
      blue:    '#1818b2'
      magenta: '#b218b2'
      cyan:    '#18b2b2'
      white:   '#b2b2b2'
    
    # Bright colors
    bright:
      black:   '#686868'
      red:     '#ff5454'
      green:   '#54ff54'
      yellow:  '#ffff04'
      blue:    '#5454ff'
      magenta: '#ff54ff'
      cyan:    '#54ffff'
      white:   '#ffffff'

colors: *kgreenblack

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Hack
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Hack
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Hack
    # Style can be specified to pick a specific face.
    style: Italic

window:
  padding:
    x: 2
    y: 2

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

live_config_reload: true

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Add, mods: Control, action: IncreaseFontSize }
  - { key: Subtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
