# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ZSH
# Load environment variables
[ -r  ~/.config/envrc ] && . ~/.config/envrc
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# History
HISTFILE=~/.cache/zsh/history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory # append history list instead replace it
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks   # remove superfluous blanks from history items

# Source from other files
source ~/.config/aliases
source ~/.config/functions

# ZSH Options
setopt always_to_end # move cursor to end if word had one match
setopt auto_cd       # cd by typing the dir name if its not a command name
setopt auto_list     # automatically list choices on ambiguous completion
setopt auto_menu     # automatically use menu completion
setopt completealiases # complete aliases
setopt correct_all   # autocorrect commandsl
setopt menucomplete
setopt nomatch 			 # print error if generation pattern has no match
setopt notify        # status of the jobs inmediately
setopt pushd_ignore_dups # don't push multiple copies of same dir to stack

# Completions
autoload -Uz compinit
compinit 
# zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' menu select
# Complete the alias when _expand_alias is used as a function
zstyle ':completion:*' complete true

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
