# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ZSH
# Load environment variables
[ -r  ~/.config/envrc ] && . ~/.config/envrc
# oh-my-zsh
export ZSH=/usr/share/oh-my-zsh
# ZSH_THEME="robbyrussell"
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
plugins=(git z)

# History
HISTFILE=~/.cache/zsh/history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks   # remove superfluous blanks from history items

# Source from other files
source ~/.config/aliases
source ~/.config/functions
source $ZSH/oh-my-zsh.sh

# Autoload
autoload -Uz compinit
compinit

# ZSH Options
setopt auto_cd       # cd by typing the dir name if its not a command name
setopt correct_all   # autocorrect commandsl
setopt auto_list     # automatically list choices on ambiguous completion
setopt auto_menu     # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match
setopt completealiases # complete aliases
setopt appendhistory # append history list instead replace it
setopt nomatch 			 # print error if generation pattern has no match
setopt notify        # status of the jobs inmediately

# IDK
zstyle ':completion:*' menu select
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' completer _expand_alias _complete _ignored

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
