" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" Plugins configuration
" This autoinstalls vim-plug inf not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.

" Markdown highlight and preview
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }

" Nerdtree
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'

" Tpope
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sensible'

" Airline
Plug 'vim-airline/vim-airline'

" Colorscheme
Plug 'morhetz/gruvbox', { 'as': 'gruvbox'}
Plug 'atahabaki/archman-vim', { 'as': 'archman'}

" LSP and auto complete plugins
Plug 'neoclide/coc.nvim'

" Higlight the letters to be faster moving in lines
Plug 'unblevable/quick-scope'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Global config

syntax on

" See the left row numbers and relative row number
set number
set relativenumber
" Yank and paste outside Vim
set clipboard=unnamed
" Let use mouse a bit
set mouse=a
" Show a line where cursor is
set cursorline
" Indent correctly
set autoindent
" Allow undo even if the file has been closed
set undofile
set undodir=/tmp
" Map leader to space
let mapleader = " "
" Quickly cancel search highlighting
nnoremap <leader><space> :nohlsearch<cr>
" Move buffer
nnoremap <leader>bn :bNext<cr>
" No backup of files needed
set nobackup
set nowritebackup

" Colors
" Colorscheme
colorscheme archman
" Change colors of pmenu 
" hi Pmenu ctermbg=240
" hi PmenuSel ctermbg=40 ctermfg=0

" Autocommands
" Stoled from https://github.com/CKolkey/.dotfiles/blob/master/nvim_init.vim
" Autoreload changed files
    set autoread
    augroup autoreadfiles
      autocmd!
      autocmd CursorHold,CursorHoldI * checktime
      autocmd FileChangedShellPost * echohl WarningMsg | echo "File changed on disk - Buffer reloaded" | echohl None
    augroup END

" Autosave current buffer
  augroup autosavebuffer
    autocmd!
    autocmd InsertLeave * nested silent! update
  augroup end

" Relative line numbers in normal mode, absolute numbers in insert mode
    augroup numbertoggle
      autocmd!
      autocmd InsertLeave * set relativenumber
      autocmd InsertEnter * set norelativenumber
    augroup END

" Autosource vimrc on save
    augroup autosource
      autocmd!
      autocmd BufWritePost $MYVIMRC nested source $MYVIMRC
    augroup END

" Load the folder with plugins config, has to be at the end.
runtime! config-plugins/**.vim
